let perguntas = [
["Você precisa vencer com um time de lutadores para completar a conquista dos Piratas do Buggy.", true],
["A recompensa de um pirata reflete a força dele.", false], 
["Antes dos eventos da guerra, Jesus Burgess tinha uma recompensa de 200,000,000 de berry.", false], 
["O verdadeiro nome do Mr. 1 é Daz Bones.", true], 
["[GLA] Atum é a melhor comida que você pode comprar de um NPC em termos de cura por segundo para um personagem level 70. ", false], 
["[GLA] Kumo Island é a única ilha sem uma instância do Black Market por perto.", false], 
["[GLA] Você pode usar a mesa de construção nas docas para transformar 10 poções pequenas de experiência em 1 poção média de experiência.", false],
["[GLA] Você pode usar a mesa de construção nas docas para transformar 10 poções médias de experiência em 1 poção grande de experiência.", false],
["Portgas D. Ace é filho do Gold Roger.", true], 
["[GLA] É possível cozinhar alguns alimentos na casa da Nojiko.", true], 
["Caesar comeu a Shiro Shiro no Mi.", false], 
["[GLA] Ninjin, um dos Piratas do Usopp, dá algumas missões em Syrup Village.", true], 
["[GLA] O kit de reparo 1.0 restaura 12.000 pontos de vida do seu navio em 20 segundos.", true], 
["[GLA] O kit de reparo 2.0 restaura 22.500 pontos de vida do seu navio em 20 segundos.", true],
["[GLA] O kit de reparo 3.0 restaura 36.000 pontos de vida do seu navio em 20 segundos.", true],
["[GLA] O kit de reparo 4.0 restaura 54.000 pontos de vida do seu navio em 20 segundos.", true], 
["[GLA] O Kit de Reparo 1.0 restaura 600 pontos de vida do seu navio por segundo.", true], 
["[GLA] O Kit de Reparo 2.0 restaura 1.125 pontos de vida do seu navio por segundo.", true], 
["[GLA] O Kit de Reparo 3.0 restaura 1.800 pontos de vida do seu navio por segundo.", true], 
["[GLA] O Kit de Reparo 4.0 restaura 2.700 pontos de vida do seu navio por segundo.", true], 
["Yasopp nasceu no East Blue, em Syrup Village.", true],
["Brook está morto há 50 anos.", false],
["A recompensa do Dellinger era de 12,000,000 de berry antes de ser congelada em razao do Doflamingo ter se tornado um Shichibukai.", false], 
["Buggy era um Shichibukai.", true], 
["A recompensa da Jewelry Bonney é de 140,000,000 de berry.", true], 
["[GLA] Erros no jogo devem ser reportados usando o atalho CTRL + R.", true], 
["A recompensa da Curly Dadan é de 7,800,000 de berry.", true], 
["Vasco Shot é o capitão do oitavo navio, liderando a oitava frota do Teach.", true],
["[GLA] É possível criar Medalhas Dinâmicas de Bronze por 5 Moedas Piratas no Mercado Negro.", true],
["[GLA] Você precisa alimentar um prisioneiro na Quest da Ririka.", false], 
["A recompensa dos Shichibukai pode aumentar.", false], 
["Baby Five nasceu no North Blue.", true], 
["Pagaya é uma estrela do mar que é mascote da Camie e também professor. Ele é o criador de uma linha de moda.", false], 
["[GLA] Em regra, emotes são desbloqueados no nível 25.", true], 
["A segunda recompensa conhecida do Capone 'Gang' Bege era de 300,000,000 berry.", true],
["Pekoms tem uma impressionante recompensa de 330,000,000 de berry.", true],
["Trebol é usuário de Haki do Armamento e da Observação.", true], 
["O nome verdadeiro do Mr.5 é Rem.", false], 
["O nome verdadeiro da Miss Merry Christmas é Drophy.", true], 
["Dracule Mihawk é um Shichibukai e membro dos Piratas do Ruivo.", false], 
["Zephyr é um personagem non-canon.", true], 
["A recompensa do Tamago é de 429,000,000 de berry.", true],
["[GLA] Erros no jogo devem ser reportados no servidor do Discord.", false], 
["[GLA] Kiribachi é um item que pode ser usado por todas as classes, exceto especialista.", false],
["[GLA] Em regra, emotes são desbloqueados no nível 40.", false], 
["[GLA] Anel da Cruz é um item recomendado para nível 50.", false],
["Avalo Pizarro é o capitão do quarto navio, liderando a quarta frota do Teach.", true], 
["Caribou nasceu no West Blue.", false],
["Urouge é também conhecido como Mad Monk. Ele é um pirata de uma ilha do céu e capitão dos Mad Monk Pirates.", false], 
["A recompensa do Mr.4 é de 3,000,000 de berry.", false],
["O cabelo do Charlotte Cracker é verde.", false], 
["[GLA] O sangramento de Killer pode acumular até 4 vezes usando mais Bloody Cuts ou Kira Nokogiri.", false],
["Katakuri pode ver 5 minutos no futuro.", false], 
["Foxy nasceu no East Blue. ", false],
["Pearl é o comandante da segunda unidade dos Piratas do Krieg.", true], 
["[GLA] É possível criar Poção Pequena de EXP no Mercado Negro.", false],
["Após a morte do Barba Branca, o Barba Marrom fugiu e assumiu o controle de Foodvalten.", true], 
["Existem Frutas do Diabo que ainda não foram catalogadas e, portanto, desconhecidas.", true],
["[GLA] O uso do Kit de Reparo é interrompido se você receber qualquer ataque de um inimigo. ", true], 
['A espada do Shiryu é uma Meito chamada "Rain".', false],
["Van Augur nasceu no East Blue.", true], 
['A alcunha do Doc Q, "Shinigami" ou deus da morte, vem do fato dele gostar de brincar com a vida das pessoas, assim como um shinigami.', true],
["Buggy foi o primeiro vilão a aparecer na série que era usuário de uma Fruta do Diabo. Ele foi também o primeiro usuário de uma fruta do diabo com quem Luffy lutou.", true], 
["[GLA] Espada Dadao é um item recomendado para nível 10.", false],
["Shojo é um membro dos Rumbar Pirates.", false], 
["[GLA] Samui Island é recomendada para jogadores do level 20 a 28 no minimapa do jogo.", true],
["[GLA] Bugs no jogo devem ser reportados no Discord.", false], 
["A recompensa do Mr.2 é de 32,000,000 de berry.", true],
["[GLA] Quando Bonney usa sua habilidade Unbridled Power, ela transforma todos à sua volta em bebês e fica invulnerável por 9 segundos. ", false], 
["[GLA] Você pode comprar duas abas extras do Stash. A primeira custa 150.000 berry e a segunda 200.000 berry.", false],
["Dalton nasceu em Drum Island.", true], 
["A maior recompensa conhecida é de 1,500,000,000 de berry.", false],
["Buggy tem a menor recompensa entre os Shichibukai.", true], 
["Vergo foi o primeiro Corazón.", true],
["Madame Shyarly é a irmã do Hatchan.", false], 
["A recompensa de Mont Blanc Cricket é de 25,000,000 de berry.", true],
["[GLA] É possível criar Medalhas Dinâmicas de Bronze por 6 Moedas Piratas no Mercado Negro.", false], 
["[GLA] Você pode comprar duas abas extras do Stash. A primeira custa 100.000 berry e a segunda 200.000 berry.", false],
["Kalgara foi revelado como um usuário de Haki do Armamento.", false], 
["Barba Negra é um Almirante dos Piratas do Barba Negra e membro dos Shichibukai.", false],
["O verdadeiro nome do Mr.2 é Bentham.", true], 
["A recompensa do Mr.5 é de 9,000,000 de berry.", false],
["O projeto da Pluton ainda não foi descoberto.", false], 
["Rob Lucci nasceu na Grand Line.", true],
["A comida favorita do Marco é uva.", false], 
["[GLA] O level necessário para fazer a Quest do Capitão Morgan é 17.", false],
["A primeira recompensa da Nico Robin foi de 78,000,000 de berry, a mesma quantia de sua mãe Nico Olivia.", false], 
["[GLA] Capone Gang Bege não libera nenhuma habilidade no nível 100.", false],
["Kin'emon comeu a Fuku Fuku no Mi.", true], 
["[GLA] Capone Gang Bege e seus aliados ficam imunes dentro do Big Father.", false],
["A comida favorita da Sugar é uva.", true], 
["Punk Hazard pode ser encontrado com um Log Pose.", false],
["Mohji é um pirata e o imediato dos Piratas do Buggy, bem como um membro da Aliança do Buggy e Alvida.", true], 
["[GLA] Spider e Giant Spider são os únicos inimigos em Kumo Island.", false],
["Mr.4 nasceu no East Blue.", false], 
["A recompensa do Gladius era de 31,000,000 de berry antes de ser congelada em razão do Doflaming ter se tornado um Shichibukai.", true],
["Miss Valentine nasceu no West Blue.", true], 
["[GLA] Fuyuki é o avô do Sora.", true],
["Sanji nasceu no South Blue.", false], 
["Nami foi o terceiro membro a entrar na tripulação dos Chapéus de Palha.", false],
["Diamond Jozu comeu a Kira Kira no Mi, fazendo com que ele se transforme em um diamante humano com uma resistência incomparável.", true], 
["Portgas D. Ace era o comandante da segunda divisão dos Piratas do Barba Branca.", true],
["[GLA] Luffy recebe menos dano dos ataques do Vinsmoke Niji porque seu corpo tem propriedades de borracha.", false], 
['Otohime era conhecida pela alcunha "Encarnação do Amor" devido à sua incrível bondade e busca pela paz entre diferentes espécies.', true],
['O nome do navio que o Mr.1 e a Miss Doublefinger usavam em suas operações era "Kill Season".', false], 
["[GLA] Jose, discípulo de Carmen, está na biblioteca de Loguetown.", true],
["A comida favorita do Teach é torta de maçã.", false], 
["Jesus Burgess é o navegador dos Piratas do Barba Negra.", false],
["Aokiji comeu a Yuki Yuki no Mi.", false], 
["A recompensa do Urouge é de 100,000,000 de berry.", false],
["Laffitte, O Supersônico, é um atirador extremamente habilidoso dos Piratas do Barba Negra.", false], 
["Mr.5 nasceu no West Blue.", false],
["[GLA] Existem 28 conquistas para completar no modo história das missões especiais do East Blue.", true], 
["[GLA] Helmeppo está localizado no mesmo prédio que seu pai Morgan.", false],
['A espada de Shiryu é uma Meito chamda "Raiu".', true], 
["[GLA] A rotação semanal muda toda sexta-feixa.", true],
["A recompensa do Gecko Moria é de 320,000,000 de berry.", true], 
["[GLA] Kuro causa 25% a mais de dano quando ataca inimigos pelas costas.", false],
["[GLA] Slime é um inimigo exclusivo de Loguetown.", false], 
["Kuroobi é um oficial dos Piratas do Sol e ex-membro dos Piratas do Arlong.", false],
["Killer é um pirata do South Blue e membro do Kid Pirates.", true], 
["Neptune é um personagem do One Piece.", true],
["Mihawk tornou-se famoso antes da Grande Era dos Piratas sequer começar.", true], 
["A recompensa do Lao G era de 61,000,000 de berry antes de ser congelada em razão do Doflamingo ter se tornado um Shichibukai.", true],
["[GLA] Há uma prisioneira chamada Tina no Arlong Park.", true], 
["Luffy derrotou Sabo em um duelo durante a infância.", false],
["Nico Robin é conhecida como a Criança Demônio.", true], 
["Zeff perdeu sua perna esquerda para salvar Sanji.", false],
["Dorry nasceu em Elbaf.", true], 
["Trebol tinha uma fruta do diabo do tipo Logia.", false],
["[GLA] Existem dois baús de ouro em Loguetown.", true], 
["[GLA] Capone Gang Bege é o único personagem que pode convocar dois subordinados sem esperar o tempo de recarga.", true],
["A dubladora do Chopper foi alterada em alguns episódios.", true], 
["Buggy é capitão do Clown Pirates e também colíder da Aliança do Buggy e Alvida.", false],
["Doc Q é o médico dos Piratas do Barba Negra.", true], 
["[GLA] Há um mapa na casa da Nojiko.", true],
["Crocodile nasceu na Grand Line.", true], 
["[GLA] Em regra, a terceira habilidade do personagem é desbloqueada no nível 10.", false],
["[GLA] Você pode conseguir o item Colar de Saru em qualquer Missão Difícil do East Blue.", false], 
["A recompensa atual do Monkey D. Luffy é de 1,500,000 de berry.", false],
["A recompensa do Trebol era de 100,000,000 de berry antes de ser congelada em razão do Doflamingo ter se tornado um Shichibukai.", false], 
["Enquanto a fruta do Borsalino é sobre velocidade, ele é bastante lento quando se trata de falar ou agir.", true],
["Demaro Black, capitão dos Falsos Chapéus de Palha, nasceu no West Blue.", false], 
["Em razão dos seus crimes, Sanjuan Wolf foi preso em Impel Down. O modo que eles encontraram para mantê-lo preso foi através de uma cela gigante no level 7.", false],
["Barba Branca nasceu na Sphinx Island no Novo Mundo.", true], 
["A recompensa da Baby Five é de 23,000,000 de berry.", false],
["Baby Five nasceu na Grand Line.", false], 
['O Red Hawk do Luffy é uma homenagem ao "Hiken" do Ace.', true],
["Jinbe é o Navegador dos Piratas do Chapéu de Palha.", false], 
["Cada um dos quatro principais membros da tripulação do Shanks são de diferentes oceanos.", true],
["[GLA] Em regra, a quarta habilidade do personagem é desbloqueada no nível 18.", false], 
["A cor do cabelo da mãe da Nico Robin é branco.", true],
["Foi confirmado que Usopp despertou o Haki da Observação durante o arco de Punk Hazard.", false], 
["Monkey D. Garp nasceu no East Blue.", true],
["Momoo é macho.", true], 
["Nefertari Vivi é um membro dos Piratas do Chapéu de Palha.", false],
["Mr.5 pode comer coisas explosivas e sua comida favorita é pólvora.", true], 
["Genzo também é um médico.", false],
["Masira e Shoujo têm uma recompensa de 23,000,000 e 26,000,000 de berry, respectivamente.", false], 
["Poseidon é uma das armas antigas.", true],
["[GLA] Nico Robin pode construir pontes com a habilidade Delphinium.", true], 
["Diamante é usuário do Haki da Observação e do Armamento.", true],
["[GLA] Camisa de Tritão é o item mais caro que o Genzo vende e custa 10.000 berry.", true], 
["Salome é uma serpente fêmea.", true],
["Sanjuan Wolf é o capitão do sétimo navio, liderando a sétima frota do Teach.", true], 
["[GLA] Sayuri, Asuya e Cherry são nomes de NPC's do Baratie.", false],
["[GLA] Você pode usar a mesa de construção nas docas para transformar 5 poções médias de experiência em 1 poção grande de experiência.", false], 
["[GLA] Gear Third é a habilidade mais forte do jogo em termos de poder.", true],
["[GLA] O stash VIP tem espaço para 100 itens.", true], 
["Oars é um gigante.", true],
["[GLA] Você precisa vencer com um time de atiradores para completar a conquista dos Piratas do Buggy.", false], 
["Sugar ficou permanentemente traumatizada com o rosto do Usopp, tornando-se um trauma incurável.", true],
["Gura Gura no Mi é uma Fruta do Diabo do tipo Logia.", false], 
["Boa Marigold e Boa Sandersonia têm Haki da Observação e do Armamento.", true],
["Barba Branca foi o responsável por cicatrizar o olho de Shanks com sua arma de garras.", false], 
["A atual recompensa da Boa Hancock é 79,000,000 de berry.", false],
["[GLA] Basil Hawkins pode usar sua passiva chamada The Magician para trocar de lugar com seus fantoches.", false], 
["O anime One Piece é o maior já feito.", false],
["O nome verdadeiro do Mr.4 é Babe, provavelmente em referência ao famoso jogador de baseball Babe Ruth.", true], 
["A recompensa do Donquixote Doflamingo é de 340,000,000 de berry.", true],
["Trafalgar Law é o capitão e doutor dos Heart Pirates.", true], 
["Haki é um misterioso poder que se encontra dentro de todos os seres vivos do mundo.", true],
["[GLA] Picareta de Mineração é um item para cortantes e tanques.", false], 
["Barba Branca nasceu na Sphinx Island no North Blue.", false],
["[GLA] O Kit de Reparo 2.0 restaura 700 pontos de vida do seu navio por segundo.", false], 
["Avalo Pizarro era originalmente rei de um país no North Blue.", true],
["[GLA] Mellorine é o nome da passiva do Sanji.", false], 
["A cera do Mr.3 é tão dura quanto o aço.", true],
["Buffalo nasceu no North Blue.", true], 
["Enel está na Lua.", true],
["[GLA] Mohji perde energia enquanto está em batalha.", true], 
["Nico Robin também é conhecida como Miss Allsunday.", true],
["[GLA] Não é possível subir no segundo andar da loja do Ippon-Matsu em Loguetown.", true], 
["Lucky Roo foi um dos últimos membros a entrar na tripulação do Shanks após ele formar os Piratas do Ruivo.", false],
["Buffalo nasceu na Grand Line.", false], 
["Izo nasceu em Wano.", true],
["Eustass Kid perdeu seu braço esquerdo.", true], 
["Lucky Roo foi quem originalmente conseguiu a Gomu Gomu no Mi de um navio pirata inimigo.", true],
["Akira Toriyama é o criador do One Piece.", false], 
["Apesar da aparência deles, Masira e Shoujo são humanos.", true],
["[GLA] Você precisa vencer com um time de usuários de Fruta do Diabo para completar a conquista da Base da Marinha.", true], 
["Pekoms comeu a Kame Kame no Mi, que o permite se transformar em uma tartaruga, dando a ele um casco duro como diamante.", true],
["A recompensa do Kuroobi é de 8,000,000 de berry.", false], 
["Rebecca pode usar o Kenbunshoku no Haki.", true],
["[GLA] É possível fazer missões diárias de Tritão em Cocoyasi Village.", true], 
["A recompensa do Killer é de 200,000,000 de berry.", true],
["Dracule Mihawk teve apenas um dublador durante todo o anime.", false], 
["[GLA] Mes é a habilidade mais forte do jogo em termos de poder.", false],
["Smoker é usuário do Haki do Armamento e da Observação.", true], 
["Buggy e Shanks estão na mesma tripulação.", false],
["A recompensa da Baby Five é de 17,000,000 de berry.", false], 
["Jinbe é o timoneiro dos Piratas do Chapéu de Palha.", true],
["Gin é um pirata e membro dos Piratas do Krieg.", true], 
["A primeira recompensa da Nico Robin foi de 79,000,000 de berry, a mesma quantia de sua mãe Nico Olivia.", true],
['Nico Robin é referida como "Luz da Revolução" pelo Exército Revolucionário.', true], 
["Avalo Pizarro é o capitão do terceiro navio, liderando a terceira frota do Teach.", false],
["Daddy Masterson é um personagem non-canon.", true], 
["Franky era originalmente líder da Família Franky e agora é capitão dos Cyborg Pirates.", false],
["Doflamingo é usuário de Haki do Armamento e do Rei apenas.", false], 
["Avalo Pizarro era originalmente rei de um país no West Blue.", false],
["[GLA] Cocoyasi Village é recomendado para jogadores do level 48 a 60 no minimapa do jogo.", false], 
["[GLA] Alvida, Don Krieg, Gin e Pearl são os únicos bosses de missão especial que não aparecem nos spawns das ilhas.", false],
["[GLA] Baratie é o primeiro local em que você pode construir um navio nível 3.", true], 
["Emporio Ivankov nasceu no West Blue.", false],
["Catarina Devon é a capitã do sexto navio, liderando a sexta frota do Teach.", true], 
["[GLA] Cerveja Forte é a melhor comida que você pode comprar de um NPC em termos de cura por segundo para um personagem level 70.", false],
["O Exército Revolucionário foi fundado em algum momento entre a morte de Roger e o nascimento de Luffy.", true], 
["Kenbunshoku no Haki garante ao usuário o sexto sentido do mundo ao seu redor e habilidades precognitivas limitadas.", true],
["Franky foi o sétimo membro a entrar na tripulação dos Chapéus de Palha.", false], 
["Tamago comeu a Tama Tama no Mi, que o permite ciclar entre diferentes formas.", true],
["[GLA] Nico Robin pode construir pontes com a habilidade Campo de Flores.", true], 
["Os Unluckies nasceram na Grand Line.", true],
["[GLA] Tamanegi, um dos piratas do Usopp, dá algumas missões em Syrup Village.", true], 
["Kuro, também conhecido pelo seu apelido Klahadore, é o capitão dos Piratas Neko.", false],
["Kid e Killer são irmãos. Juntos, formaram os Piratas do Kid.", false], 
["Haoshoku no Haki concede ao usuário um sexto sentido do mundo ao seu redor e habilidades precognitivas limitadas.", false],
["Jinbe é um membro dos Piratas do Chapéu de Palha e ex-Shichibukai.", true], 
["Golden Lion Shiki é um personagem non-canon.", false],
["Masira e Shoujo são irmãos.", false], 
['Doflamingo e Viola tiveram uma "complexa" relação amorosa.', true],
["Momoo desenvolveu um trauma a respeito do Luffy e do Zoro, sofrendo um ataque de pânico só de vê-los.", false], 
["Tamago perdeu o olho esquerdo para o Pedro.", true],
["Luffy tem uma Fruta do Diabo do tipo Logia que tornou seu corpo de borracha.", false], 
["Sadi nasceu na Grand Line.", true],
["Edward Newgate é loiro.", true], 
["Momoo desenvolveu um trauma a respeito do Luffy e do Sanji, sofrendo um ataque de pânico só de vê-los.", true],
["Van Augur, o supersônico, é um Sniper dos Piratas do Barba Negra e um excelente atirador.", true], 
["[GLA] A rotação semanal muda todo sábado.", false],
["[GLA] Personagens diamante são 7% mais fortes que personagens ouro.", true], 
["A atual recompensa do Bepo é de 500 berry.", true],
["Carina era amiga da Nami no East Blue.", true], 
["Vista nasceu na Grand Line.", false],
["[GLA] Syrup Village é a única ilha com duas entradas de doca no East Blue.", false], 
["Tsuru comeu a Washe Washe no Mi.", false],
["A comida favorita do Doflamingo é lagosta.", true], 
["Assim como Kuzan, Smoker deseja acabar com o sistema de Shichibukai.", false],
["Antes dos eventos da guerra, Laffitte tinha uma recompensa de 42,200,000 de berry.", true], 
["Koala é um humano que pode usar o karatê tritão.", true],
['O nome do navio que o Mr.1 e a Miss Doublefinger usavam em suas operações era "Kill Sassoon".', true], 
["Há um tritão na família Donquixote.", true],
["Chopper experimentou algodão doce pela primeira vez durante o Davy Back Fight.", true], 
["[GLA] A habilidade da Robin, Spider Net, pode ser destruída por alguns ataques.", false],
['O nome dos navios do Masira e Shoujo é "Utan Sonar" e "Victory Hunter", respectivamente.', false], 
["Eric é um pirata non-canon que foi mostrado no anime. ", false],
["Kin'emon comeu a Tuku Tuku no Mi.", false], 
["Sengoku nasceu no South Blue.", true],
["[GLA] Orange Town é recomendada para jogadores do level 20 a 30 no minimapa do jogo.", false], 
["Antes dos eventos da guerra, Doc Q tinha uma impressioannte recompensa de 72,500,000 de berry.", false],
["Atualmente o cabelo do Arlong é roxo.", false], 
["Frost é um personagem de One Piece.", false],
["[GLA] Enquanto está em chamas, Pearl tem as seguintes habilidades: Fire Pearl Shot, Fire Present, Fire Pearl Close e Fire Pearl Daitokuten.", false], 
["A mãe do Usopp nasceu no South Blue.", false],
["Kuroobi é um oficial dos Piratas do Arlong e ex-membro dos Piratas do Sol.", true], 
["Arlong era o capitão dos Piratas do Sol e tinha a maior recompensa do East Blue antes de ser derrotado pelo Monkey D. Luffy.", false],
["[GLA] É possível criar Medalhas Dinâmicas de Prata por 8 Moedas Piratas no Mercado Negro.", false], 
["Rob Lucci nasceu no West Blue.", false],
["[GLA] Genzo vende Bandana de Tritão, Calça de Tritão, Anel do Mar e Turbante do Mar por 5.000 berry cada.", false], 
["A comida favorita do Kuro é banana.", true],
["Hancock é a imperatriz do Amazon Lily, motivo pelo qual ela é chamada de Imperatriz Shichibukai.", false], 
["[GLA] Reiju pode usar sua habilidade Pink Tornado para se livrar de imobilizações.", true],
["Em alguns fillers, os personagens foram feitos pelo próprio Oda. ", true], 
["Zeus é um personagem do One Piece.", true],
["Basil Hawkins é um pirata infâme do North Blue conhecido como o Mago e capitão dos Piratas do Hawkins.", true], 
["Benn Beckman é o vice-capitão dos Piratas do Ruivo.", true],
["Bartolomeo tem a Fruta do Diabo Nikyu Nikyu no Mi.", false], 
["A recompensa do Kuro é de 6,000,000 de berry.", false],
["Diamond Jozu comeu a Mira Mira no Mi, fazendo com que ele se transforme em um diamante humano com uma resistência incomparável.", false], 
["[GLA] Pearl não pode usar nenhuma habilidade enquanto Iron Wall estiver ativo.", true],
["[GLA] Samui Island é recomendada para jogadores do level 18 a 26 no minimapa do jogo.", false], 
["Smoker é usuário do Haki do Armamento apenas.", false],
["Sandai Kitetsu (uma das espadas do Zoro) enferrujou.", false], 
["O verdadeiro nome do Mr.3 é Baldino.", false],
["A recompensa do Mr.4 é de 3,200,000 de berry.", true], 
["Monet tinha uma Fruta do Diabo do tipo Paramecia.", false],
["[GLA] Island of Rare Animals é recomendada para jogadores do level 38 a 50 no minimapa do jogo.", false], 
["[GLA] Quando o Alligator selvagem morre, o sangramento aplicado por ele perde o efeito.", true],
["[GLA] Billy McShooty é um inimigo em Orange Town.", false], 
["Shanks nasceu no East Blue.", false],
["Issho é um Almirante da Marinha.", true], 
["A recompensa do Jinbe era de 250,000,000 de berry antes dele se tornar um Shichibukai.", true],
["[GLA] Você pode iniciar uma missão diária de derrotar Slimes em Samui Island.", false], 
["[GLA] Você precisa alimentar um prisioneiro na Quest da Rika.", true],
["Miss Goldenweek não comeu uma Fruta do Diabo.", true],
["O nome verdadeiro da Miss Goldenweek é Drophy.", false],
["[GLA] Loguetown é recomendada para jogadores do level 60 a 70 no minimapa do jogo.", true],
["Desde quando Mr.1 era uma criança, ele sempre quis ser um herói. Todavia, os ideais dele se distorceram bastante, transformando-o em um assassino implacável.", true],
["A recompensa do Gin é de 12,000,000 de berry.", true],
['O nome dos navios do Masira e do Shoujo são "Victory Hunter" e "Utan Sonar", respectivamente.', true],
["A recompensa do Tamago é de 429,500,000 de berry.", false],
["A recompensa do Zeff é de 47,600,000 de berry.", false],
["[GLA] Shanks imobiliza inimigos em volta dele com a habilidade Busoshoku Haki Waves.", false],
["[GLA] Há um baú escondido atrás da mansão da Kaya.", true],
["Bacura é um usuário da Fruta do Diabo do tipo Zoan.", false],
["Em razão dos seus crimes, Sanjuan Wolf foi preso em Impel Down. O modo que eles encontraram para mantê-lo preso foi através de uma cela gigante no level 6.", true],
["Busoshoku no Haki garante ao usuário um sexto sentido do mundo ao seu redor e habilidades precognitivas limitadas.", false],
["[GLA] Alvida Pirates é a única Missão Especial do modo história sem uma versão no modo difícil.", false],
["Momoo é fêmea.", false],
["Hatchan tem 8 braços. ", false],
["[GLA] O Kit de Reparo 3.0 restaura 30.000 pontos de vida do seu navio em 30 segundos.", false],
["[GLA] Em regra, a quinta habilidade do personagem é desbloqueada no nível 25.", false],
["Marco era o comandante da Segunda Divisão e mão direita do Barba Branca.", false],
["Laboon é macho.", true],
["A recompensa do Jinbe é de 439,000,000 de berry.", false],
["A recompensa do Mr.3 é de 24,000,000 de berry.", true],
["Mihawk não é o único com uma recompensa desconhecida entre os Shichibukai.", false],
["Shiryu nasceu na Grand Line.", true],
["Kid e Killer são amigos de infância. Juntos, formaram os Piratas do Kid.", true],
["A recompensa atual do Marshall D. Teach é de 2,247,600,000 de berry.", true],
["Kin'emon pode se comunicar através de peidos, fazendo eles soarem como a linguagem humana.", true],
["[GLA] Buchi pode usar a habilidade Take the Lead para chamar Sham para lutar ao lado dele.", false],
["Benn Beckman não tem uma recompensa.", false],
["[GLA] Trafalgar Law pode quebrar paredes com a habilidade Injection Shot.", true],
["Laffitte nasceu no West Blue.", true],
["[GLA] Muggy Dama é a habilidade que o Buggy libera no nível 100.", false],
["Sanjuan Wolf nasceu no West Blue.", true],
["Mr.2 tem o mesmo dublador do Franky e do Jango.", true],
["Caso o Governo Mundial soubesse que o Crocodile era o chefe da Baroque Works, a recompensa dele seria no mínimo dobrada para 162,000,000 de berry.", true],
["O verdadeiro nome da Miss Doublefinger é Zala.", true],
["[GLA] Chopper ganha defesa bônus durante a habilidade Walk Point.", true],
["Crocodile nasceu no North Blue.", false],
['O navio que a Hancock e as Piratas Kuja navegam é chamado de "Aroma Snake".', false],
["Arlong era o capitão dos Piratas do Arlong e tinha a maior recompensa do East Blue antes de ser derrotado pelo Monkey D. Luffy.", true],
["Marco comeu a Tori Tori no Mi, tipo: Fênix, uma Zoan Mítica.", true],
["Shanks nasceu no West Blue.", true],
["Bartholomew Kuma é um Shichibukai e um ex-oficial do Exército Revolucionário.", true],
["A recompensa do Mr.3 é de 23,000,000 de berry.", false],
["Jesus Burgess é o timoneiro dos Piratas do Barba Negra.", true],
["Após ser diagnosticado com sua doença, Gol D. Roger levou três anos para encontrar o One Piece.", true],
["[GLA] Boa Hancock pode transformar os inimigos em pedra por 7 segundos com a habilidade Mero Mero Mellow. ", true],
["Sogeking na verdade é o Usopp.", true],
["[GLA] Daddy McShooty é um inimigo em Loguetown.", false],
["Bellamy se retirou oficialmente como um pirata e agora se dedica a pintura de bandeiras.", true],
["A recompensa do Daz Bones é de 75,000,000 de berry.", true],
["Miss Doublefinger nasceu no South Blue.", false],
["Pandaman está na tripulação do Trafalgar Law.", false],
["A recompensa do Lao G era de 60,000,000 de berry antes de ser congelada em razão do Doflamingo ter se tornado um Shichibukai.", false],
["[GLA] Você pode comprar duas abas extras do Stash. A primeira custa 150.000 berry e a segunda 300.000 berry.", true],
["Sabo comeu a Mera Mera no Mi.", true],
["Sugar ficou permanentemente traumatizada com o rosto do Zoro, tornando-se um trauma incurável.", false],
["Crocodile estava atrás da Uranus, uma das armas antigas.", false],
["Shakky ajudou a abrigar as Gorgon Sisters depois que elas escaparam dos Nobres Mundiais junto com Gloriosa e Rayleigh.", true],
["Nami conseguiu o Clima-Tact em Drum Island.", false],
["Lucky Roo nasceu no North Blue.", false],
["A maior recompensa conhecida é de 2,257,600,000 de berry.", false],
["Zoro empunhou mais de 8 espadas diferentes no anime.", true],
["Issho decidiu se cegar porque havia muitas coisas que ele não queria ver.", true],
["Basil Hawkins é um pirata infâme do North Blue conhecido como o Mago e capitão dos Piratas do Mago.", false],
["[GLA] Personagens envenenados pela Reiju recebem 50% menos cura de suportes.", true],
["Benn Beckman nasceu no East Blue.", false],
["Robin foi o sétimo membro a entrar na tripulação dos Chapéus de Palha.", true],
["Shiryu é o capitão da terceira frota do Teach.", false],
["O aniversário da Miss Valentine é no Valentine's Day, por razões óbvias.", true],
["A recompensa do Foxy é de 25,000,000 de berry.", false],
["Brook foi o último membro a entrar na tripulação dos Chapéu de Palha.", false],
["[GLA] É possível reparar os equipamentos do seu navio nas Docas.", true],
["[GLA] Você só pode trocar seus equipamentos em uma Zona Segura.", false],
["Doc Q carrega uma grande lança como arma.", false],
["A Ope Ope no Mi é também chamada de Fruta do Diabo Suprema, devido à sua habilidade de conceder vida eterna.", true],
["Gedatsu (um dos sacerdotes de Enel) agora gerencia um Resort de águas termais em Alabasta. ", true],
["Em termos simples, Haki é a habilidade de sentir energia espiritual (Kenbunshoku), usar força vital (Busoshoku) e dominar inimigos (Haoshoku).", true],
["[GLA] Você precisa vencer com um time de cortantes para completar a conquista dos Piratas da Alvida.", true],
["[GLA] Cabaji tem a menor velocidade de movimento base do jogo.", true],
["Mr.4 nasceu na Grand Line.", true],
["Benn Beckman é o vice-capitão dos Piratas do Shanks.", false],
["Antes dos eventos da guerra, Jesus Burgess tinha uma recompensa de 20,000,000 de berry.", true],
["Antes dos eventos da guerra, Van Augur tinha uma impressionante recompensa de 64,000,000 de berry.", true],
["Bellemere encontrou a Nami e a Nojiko no Reino de Oykot, no East Blue.", true],
["O nome verdadeiro do Trebol é John Trebol.", false],
["Portgas D. Ace era o comandante da segunda divisão dos Spade Pirates.", false],
["Wapol é o primeiro rei mostrado na série.", true],
["Enel está em Marte.", false],
["Python é o nome da espada do Shanks.", false],
["A cor do cabelo da Miss Valentine é verde.", false],
["A recompensa da Miss Goldenweek é de 30,000,000 de berry.", false],
["Capone Gang Bege é capitão do Fire Tank Pirates e também um dos doze piratas classificados como a Pior Geração.", true],
["[GLA] Existem Cows, Pigs, Chickens e Sheeps em Foosha Village.", true],
["[GLA] Os Kits de Reparo 1.0, 2.0 e 3.0 são vendidos na loja do Mercado Negro pelos respectivos valores: 30, 90 e 180 berry.", false],
["Shanks tem uma cicatriz no olho esquerdo.", true],
["Hatchan é um ex-oficial dos Piratas do Sol e membro dos Piratas do Arlong antes disso.", false],
["A recompensa do Machvise era de 10,000,000 de berry antes de ser congelada em razão do Doflamingo ter se tornado um Shichibukai.", false],
["Bellemere encontrou a Nami e a Nojiko no Reino de Oykot, no West Blue.", false],
["Lucky Roo foi um dos primeiros membros a entrar na tripulação do Shanks após ele formar os Piratas do Ruivo.", true],
["Ryuma tinha a sombra de um lendário samurai de Wano.", false],
["[GLA] No tutorial do jogo, o NPC que passa instruções para você é o Woop Slap, o prefeito de Foosha Village.", false],
["A recompensa do Diamante era de 100,000,000 de berry antes de ser congelada em razão do Doflamingo ter se tornado um Shichibukai.", false],
['O principal navio do Exército Revolucionário é chamado de "Viento Granma".', true],
["Miss Goldenweek fez dupla com o Mr. 3 em razão das habilidades dela de pintar as criações de cera, tornando-as mais realistas.", true],
["Catarina Devon caça qualquer MULHER que ela acha atraente e decapita a cabeça delas para adicioná-las à sua coleção pessoal.", true],
["[GLA] Syrup Village é a ilha com o maior número de entradas de doca no East Blue.", true],
["Masira e Shoujo têm uma recompensa de 23,000,000 e 36,000,000 de berry, respectivamente.", true],
["[GLA] Atualmente Pearl é o único personagem com três classes: Tanque, Especialista e Lutador.", false],
["Crocodile foi o primeiro oponente a derrotar Luffy em uma batalha.", true],
["Sanjuan Wolf é o capitão do quinto navio, liderando a quinta frota do Teach.", false],
["Enel e seus sacerdotes conquistaram a lua.", false],
["Todos os quatro principais membros da tripulação do Shanks são do mesmo oceano.", false],
["[GLA] Quando Sanji cura uma mulher, ele fica motivado e recebe um bônus de velocidade e ataque por 10 segundos.", false],
["Momoo agora é oficialmente considerado um animal de estimação dos Piratas do Arlong.", false],
["O nome verdadeiro do Hatchan é Hatchan.", true],
["Miss Goldenweek nasceu no North Blue.", true],
["[GLA] Você pode usar o atalho ALT + ENTER para colocar o jogo em tela cheia.", true],
["Rosinante comeu a Shiu Shiu no Mi.", false],
["Rosinante foi o primeiro Corazón.", false],
["A recompensa do Demaro Black é de 26,300,000 de berry.", false],
["Jinbe é oficialmente o décimo membro dos Piratas do Chapéu de Palha.", true],
["A recompensa do Foxy é de 24,000,000 de berry.", true],
["Sanjuan Wolf tem uma fruta do diabo que o permite aumentar o próprio tamanho.", true],
["Issho nasceu na Grand Line.", true],
["[GLA] Você precisa vencer com um time de suportes para completar a conquista dos Piratas do Arlong.", true],
["[GLA] Baratie é recomendado para jogadores do level 42 a 52 no minimapa do jogo.", true],
["[GLA] O Talismã da Aranha é um item que pode ser usado por todas as classes.", true],
["Trebol foi o primeiro a encontrar a Ito Ito no Mi quando era um criminoso.", true],
["[GLA] Sabo é o nome da criança que a Nojiko pede para ajudar no Arlong Park.", false],
["Como um dos principais membros do Exército Revolucionário, Koala tem uma recompensa de 320,000,000 de berry.", false],
["[GLA] Você não pode trocar seus equipamentos em batalha.", true],
['Trafalgar Law nomeou sua tripulação por causa do Corazón, como homenagem ao seu nome e porque ele "mudou seu coração" para melhor.', true],
["Barba Negra acredita legitimamente que os sonhos dos homens nunca morrerão.", true],
["[GLA] Pearl é o primeiro boss nas missão da Armada Pirata.", true],
["Stussy nasceu no West Blue.", false],
["Doflamingo é usuário do Haki da Observação, Armamento e do Rei. ", true],
["[GLA] O PvP na Grand Line será opcional.", false],
["Foi confirmado que Usopp despertou o Haki da Observação durante o arco de Dressrosa.", true],
["[GLA] Golden Hull é o nome de uma skin de navio.", true],
["Aladdin já foi um escravo.", true],
["Otohime tinha um Haki da Observação e do Armamento muito desenvolvido, o que a permitia entender profundamente a emoção dos outros.", false],
["A recompensa do Pica era de 99,000,000 de berry antes de ser congelada em razão do Doflamingo ter se tornado um Shichibukai.", true],
["Tamago é membro da tribo dos Pernas Longas.", true],
["Aisa nasceu com um Haki do Armamento avançado.", false],
["O Exército Revolucionário foi fundado após o nascimento do Luffy.", false],
["Foxy comeu a Soro Soro no Mi.", false],
["A comida favorita do Nezumi é queijo.", true],
["O nome verdadeiro do Mr.4 é Derek, provavelmente em referência ao famoso jogador de baseball Derek Jeter.", false],
["Urouge é também conhecido como Mad Monk. Ele é um pirata de uma ilha do céu e capitão dos Piratas Fallen Monk.", true],
["Barba Branca comeu a Goro Goro no Mi.", false],
["A recompensa do Trebol era de 99,000,000 de berry antes de ser congelada em razão do Doflamingo ter se tornado um Shichibukai.", true],
["[GLA] Você precisa vencer com uma equipe de HOMENS para completar a conquista da Armada Pirata.", false],
["Objetos podem comer Frutas do Diabo.", true],
["[GLA] Jutte Blow, a habilidade do Smoker, silencia somente usuários de Fruta do Diabo.", true],
["Depois do timeskip o Franky é o mais alto dos Piratas do Chapéu de Palha.", false],
["Vasco Shot é o capitão do sétimo navio, liderando a sétima frota do Teach.", false],
["[GLA] Orange Town é recomendada para jogadores do level 23 a 30 no nimimapa do jogo.", true],
["[GLA] Para melhorar um personagem de 1 para 5 estrelas você precisa usar 840 medalhas no total.", true],
["Killer é um pirata do North Blue e membro do Kid Pirates.", false],
["Akainu nasceu na Grand Line.", false],
["Johnny e Yosaku nasceram no West Blue.", false],
["Shanks foi o primeiro dono do chapéu de palha", false],
["Antes dos eventos da guerra, Doc Q tinha uma impressionante recompensa de 72,000,000 de berry.", true],
["[GLA] Island of Rare Animals é recomendada para jogadores do level 40 a 52 no minimapa do jogo.", true],
["Koala era um membro dos Piratas do Sol.", true],
["A Sniper Island está localizada na Grand Line. ", false],
["Killer perdeu um braço no Timeskip.", false],
["Demaro Black, capitão dos Falsos Chapéus de Palha, nasceu no East Blue.", true],
["[GLA] Monkey D. Luffy têm as seguintes classes: Bruiser, Lutador e Tanker.", false],
["Tsuru nasceu no North Blue.", true],
["A recompensa do Diamante era de 99,000,000 de berry antes de ser congelada em razão do Doflamingo ter se tornado um Shichibukai.", true],
["Antes dos eventos da guerra, Van Augur tinha uma impressionante recompensa de 60,000,000 de berry.", false],
["[GLA] Portgas D. Ace é um personagem Diamante.", true],
["Gryphon é o nome da espada do Shanks.", true],
["[GLA] Você precisa vencer com um time de especialistas para completar a conquista dos Piratas da Alvida.", false],
["Kin'emon é usuário de Haki do Armamento apenas.", false],
["Laffitte cresceu no West Blue, onde se tornou Marinheiro.", false],
["[GLA] Você pode encontrar 9 entradas para o Mercado Negro no East Blue.", true],
["Catarina Devon é a capitã do quinto navio, liderando a quinta frota do Teach.", false],
["Aisa nasceu com um Haki da Observação avançado.", true],
["A recompensa da Miss Valentine é de 7,500,000 de berry.", true],
["[GLA] Dracule Mihawk desacelera seus próprios aliados com a habilidade Taka no Me.", true],
["A primeira recompensa do Monkey D. Luffy foi de 30,000,000 de berry.", true],
["[GLA] A habilidade Liberation, do Marshall D. Teach, tem 2 segundos de tempo de recarga e 18 de poder.", true],
["[GLA] Sanzen Sekai é a habilidade mais forte do jogo em termos de poder.", false],
["A recompensa do Jinbe era de 200,000,000 de berry antes dele se tornar um Shichibukai.", false],
["Após os eventos em Punk Hazard, Smoker se tornou oficialmente o líder da G-5", true],
["Benn Beckman NÃO é o personagem mais inteligente que apareceu na saga do East Blue.", false],
["[GLA] Nico Robin não pode construir pontes com a habilidade Delphinium.", false],
["A recompensa do Kuroobi é de 9,000,000 de berry.", true],
["A recompensa do Fisher Tiger era de 230,000,000 de berry.", true],
["[GLA] Nefertari Vivi pode fazer uma dança sexy para motivar seus aliados, aumentando o ataque e a defesa deles por 15 segundos.", false],
["A recompensa do Senor Pink era de 56,000,000 de berry antes de ser congelada em razão do Doflamingo ter se tornado um Shichibukai.", false],
["Boa Hancock nasceu no North Blue.", false],
["Kuzan decidiu se cegar porque haviam muitas coisas que ele não queria ver.", false],
["Usopp foi o terceiro membro a entrar na tripulação dos Chapéus de Palha.", true],
["[GLA] Snowball é o nome de um coelho em Samui Island.", true],
["[GLA] Meito: Shigure é um item que pode ser usado somente por cortantes.", false],
["Dizem que Yasopp pode atirar na antena de uma formiga de muito longe.", true],
["A recompensa da Miss Merry Christmas é de 14,000,000 de berry.", true],
["Tsuru nasceu no East Blue.", false],
["A recompensa do Demaro Black é de 26,000,000 de berry.", true],
["[GLA] Você precisa vencer com um time de mulheres para completar a conquista dos Black Cat.", false],
["Barba Negra é um almirante dos Piratas do Barba Negra e membro dos Yonko. ", true],
["Lucky Roo pode parecer gordo e lento, mas na verdade ele é um lutador muito ágil e rápido.", true],
["[GLA] Há uma piscina em Shells Town, dentro da Base da Marinha.", true],
["Masashi Kishimoto é o criador do One Piece.", false],
['Otohime era conhecida pela alcunha "Reencarnação do Amor" devido à sua incrível bondade e busca pela paz entre diferentes espécies.', false],
["[GLA] Sapi é o NPC que vende Atum em Cocoyasi Village.", false],
["Shiryu é o capitão da segunda frota do Teach.", true],
["Kid e Killer são amigos de infância. Juntos, formaram os Piratas do Killer.", false],
["Pica tem uma fruta do diabo do tipo Paramecia.", true],
["[GLA] Jango é o único boss de Missão Especial que também é um NPC.", false],
["A recompensa do Zoro é maior que a do Sanji.", false],
["Os Yeti Cool Brothers são parte de uma subespécie desconhecida de humanos.", false],
["Os Yeti Cool Brothers são parte de uma subespécie desconhecida de gigantes.", true],
["[GLA] Você pode usar a mesa de construção nas docas para transformar 10 poções pequenas de experiência em 2⃣  poções médias de experiência.", false],
["Funkfreed é o nome do elefante do Spandam.", false],
["A barreira do Bartolomeo quebrou somente uma vez durante o anime.", false],
["Scratchmen Apoo é da tribo longarm, um infâme pirata com tema de música e capitão dos Piratas On Music.", false],
["[GLA] Morgan é o único boss de Missão Especial que também é um NPC.", false],
["Hatchan é um ex-oficial dos Piratas do Arlong e membro dos Piratas do Sol antes disso.", true],
["Crocodile foi o segundo oponente a derrotar Luffy em uma batalha.", false],
["Issho comeu a Zushi Zushi no Mi, que o permite manipular a gravidade.", true],
["Tamago perdeu o olho direito para o Pedro.", false],
["Kuzan nasceu no South Blue", true],
["Enel comeu a Gura Gura no Mi.", false],
["Diamante foi o primeiro a encontrar a Ito Ito no Mi quando era um criminoso.", false],
["Masira e Shoujo têm uma recompensa de 36,000,000 e 23,000,000 de berry, respectivamente.", false],
["Barba Negra nasceu no North Blue.", false],
["A maior recompensa conhecida é de 2,247,600,000 de berry.", true],
["A recompensa do Buffalo é de 13,000,000 de berry.", false],
["[GLA] Skins de navio estão disponíveis somente para navios de nível dois ou maior. ", true],
["Kin'emon é usuário de Haki da Observação e do Armamento", true],
["Após os eventos em Punk Hazard, Smoker se tornou oficialmente o líder da G-4.", false],
["[GLA] Uchimizu é uma habilidade que pode ser usada por Jinbe, Chew e Arlong.", false],
["[GLA] Fire Pearl é o nome da passiva do Pearl.", false],
["Arlong é o único indivíduo conhecido que foi libertado de Impel Down.", true],
["A recompensa da Miss Valentine é de 7,000,000 de berry.", false],
["A recompensa do Zoro era maior que a do Sanji.", true],
["A recompensa do Machvise era de 11,000,000 de berry antes de ser congelada em razão do Doflamingo ter se tornado um Shichibukai.", true],
['O nome do navio que os Piratas Donquixote usaram nos dias deles no North Blue era "Numancia Flamingo".', true],
["A recompensa do Gin é de 10,000,000 de berry.", false],
["A recompensa do Buffalo é de 15,000,000 de berry.", false],
["[GLA] Hideka é a avó do Sora.", false],
['O nome do navio do Mr.2 era "Swanda Express".', true],
["[GLA] Jinbe é o único personagem Diamante com a classe Tanque.", false],
["O aniversário da Miss Merry Christmas é no natal, por razões óbvias.", true],
["Benn Beckman é o personagem mais inteligente que apareceu na saga do East Blue.", true],
["A comida favorita de Marco é abacaxi.", true],
["Trafalgar Law comeu a Pika Pika no Mi.", false],
["[GLA] Em Cocoyasi Village você pode comprar Laranja do NPC pelo valor de 42 berry cada.", true],
["[GLA] Em regra, a terceira habilidade do personagem é desbloqueada no nível 12.", true],
["[GLA] Existem 30 conquistas para completar no modo história das missões especiais.", false],
["[GLA] Carne de Porco Gourmet é a comida mais demorada para cozinhar no Baratie. Demora 9 minutos.", true],
["O dragão contra o qual Luffy e os outros lutaram em Punk Hazard foi criado artificialmente por CAESAR em um Laboratório em Punk Hazard.", false],
["O dragão contra o qual Luffy e os outros lutaram em Punk Hazard foi criado artificialmente por VEGAPUNK em um laboratório em Punk Hazard. ", true],
["Sengoku nasceu no North Blue.", false],
["Franky é o oitavo membro da tripulação dos Chapéus de Palha.", true],
["Alvida é a antiga capitã dos Piratas da Alvida.", true],
["[GLA] Backflips e habilidades de evasão concedem imunidade a dano e imobilizações.", false],
["O nome verdadeiro do Hatchan é Hatchi.", false],
["Tsuru comeu a Woshu Woshu no Mi.", true],
["Scratchmen Apoo é da tribo longarm, um infâme pirata com tema de música e capitão dos Piratas On Air.", true],
["Pekoms comeu a Tame Tame no Mi, que o permite se transformar em uma tartaruga, dando a ele um casco duro como diamante.", false],
["[GLA] Shanks mata inimigos fracos instantaneamente com a habilidade Kenbunshoku Haki.", false],
["Machvise comeu a Ton Ton no Mi.", true],
["Gol D. Roger nasceu em Loguetown.", true],
["[GLA] O Kit de Reparo 2.0 restaura 22.000 pontos de vida do seu navio em 30 segundos.", false],
["[GLA] Kumo Island é recomendado para jogadores do level 64 a 72 no minimapa do jogo.", true],
["Doc Q é o médico dos Piratas do Barba Branca.", false],
["Benn Beckman nasceu no North Blue.", true],
["Pica é usuário do Haki do Armamento apenas.", false],
["Gin tem o mesmo dublador do Kuro.", false],
["Jinbe foi o nono membro a entrar na tripulação dos Chapéus de Palha.", false],
["[GLA] Existem Bronze berry, Silver berry, Gold berry e Diamond berry.", false],
["O  nome verdadeiro do Barba Marrom é Chadros Higelyges.", true],
["A recompensa do Chew é de 5,500,000 de berry.", true],
["[GLA] Você precisa vencer com um time de tanques para completar a conquista da Base da Marinha.", false],
["[GLA] Nami pode criar somente 3 núvens simultaneamente.", false],
["Hody Jones é o capitão dos Piratas Homens-Peixe.", false],
['A alcunha do Laffitte, "Shinigami" ou deus da morte, vem do fato dele gostar de brincar com a vida das pessoas, assim como um shinigami.', false],
["[GLA] Existem Bronze berry, Silver berry, Gold berry e Platinum berry.", true],
["Otohime tinha um Haki da Observação muito desenvolvido, o que a permitia entender profundamente a emoção dos outros.", true],
["[GLA] A habilidade Liberation, do Marshall D. Teach, tem dois segundos de tempo de recarga e 10 de poder.", false],
['O nome do navio que o Mr.5 e a Miss Valentine usavam em suas operações era "Bomb Rock Candy".', false],
["Hody Jones é o capitão dos Novos Piratas Homens-Peixe.", true],
["[GLA] Em Conomi Island você pode encontrar os seguintes inimigos: Moles, Wolves, e Small Moles.", false],
["[GLA] Para iniciar a quest do Ripper em Shells Town, você precisa primeiro completar a quest do Helmeppo.", false],
["[GLA] Um personagem Diamante precisa de mais medalhas para ter suas estrelas melhoradas do que um personagem ouro.", false],
["[GLA] Sayuri, Asuya e Chieri são nomes de NPC's do Baratie.", true],
["A recompensa do Gladius era de 30,000,000 de berry antes de ser congelada em razão do Doflaming ter se tornado um Shichibukai.", false],
["Atualmente o Monkey D. Luffy tem a maior recompensa conhecida.", false],
["Gol D. Roger usava um chapéu similar ao do Luffy.", false],
["Mohji é um pirata e capitão dos Piratas Leões.", false],
["Perona tem o mesmo dublador da Koala.", false],
["[GLA] Calça de Tritão é o item mais caro que o Genzo vende e custa 10000 berry.", false],
["[GLA] Boa Hancock não pode petrificar o Monkey D. Luffy.", true],
["[GLA] Há uma prisioneira chamada Tita no Arlong Park.", false],
["Issho nasceu no South Blue.", false],
["O gênero de Surume é feminino.", false],
["Laffitte cresceu no West Blue, onde se tornou xerife.", true],
["A recompensa do Fisher Tiger era de 200,000,000 de berry.", false],
["Catarina Devon caça qualquer HOMEM que ela acha atraente e decapita a cabeça deles para adicioná-las à sua coleção pessoal.", false],
["Monet e Sugar são irmãs.", true],
["O nome verdadeiro da Baby Five é Babi.", false],
["Atualmente Moria é o único Shichibukai conhecido (atual ou antigo) sem uma alcunha conhecida.", true],
["Vergo pode cobrir quase seu corpo inteiro com Haki.", false],
["Emporio Ivankov nasceu na Grand Line.", true],
["[GLA] Sanji não pode ser seduzido pelas mulheres enquanto o Diable Jamble estiver ativado. ", true],
["Portgas D. Ace era um usuário de Haki do Rei.", true],
["Mr.3 queria trair Crocodile desde o início do arco.", false],
["[GLA] Eustass Kid pode construir pontes com a habilidade Magnetic Pull.", true],
["[GLA] É possível criar Medalhas Dinâmicas de Diamante por 40 Moedas Piratas no Mercado Negro.", false],
["Demaro Black, Manjaro, Chocolat, Drip, Turco, Cocoa, MountBLUTAIN e Nora Gitsune são os nomes verdadeiros da falsa tripulação dos Chapéus de Palha.", true],
["Kureha nasceu em Drum Island.", true],
["Pekoms tem uma impressionante recompensa de 300,000,000 de berry", false],
["Koala está lutando no Exército Revolucionário para mudar o mundo de uma forma que os Tritões e as Sereias sejam tratados como pessoas normais.", true],
["A recompensa do Pica era de 100,000,000 de berry antes de ser congelada em razão do Doflamingo ter se tornado um Shichibukai.", false],
["Momoo agora é oficialmente considerado um animal de estimação dos Piratas do Caribou.", true],
["Capone Gang Bege é capitão do Castle Tank Pirates e também um dos doze piratas classificados como a Pior Geração.", false],
["[GLA] Em regra, a quarta habilidade do personagem é desbloqueada no nível 20.", true],
["Kanjuro comeu a Draw Draw no Mi, que o permite trazer à vida tudo o que ele desenha.", false],
['Nico Robin é referida como "Demônio da Revolução" pelo Exército Revolucionário.', false],
["Zeff perdeu sua perna direita para salvar Sanji.", true],
["Mr.3 agora é reconhecido como um 'executivo' dos Piratas do Buggy.", true],
["[GLA] Você pode encontrar 8 entradas para o Mercado Negro no East Blue", false],
["[GLA] Baratie é recomendado para jogadores do level 42 a 50 no minimapa do jogo.", false],
["Oars é um meio-gigante.", false],
["Pell nasceu em Alabasta.", true],
["[GLA] O Kit de Reparo 1.0 restaura 450 pontos de vida do seu navio por segundo.", false],
["Stussy nasceu na Grand Line.", true],
["Miss Doublefinger nasceu na Grand Line.", true],
["Akainu tem o mesmo dublador do Krieg.", true],
["Após ser diagnosticado com sua doença, Gol D. Roger levou dois anos para encontrar sua recompensa.", false],
["Pekoms tem uma Fruta do Diabo do tipo Zoan.", true],
["Hody Jones e seus companheiros não possuem recompensa.", true],
["Trafalgar Law é conhecido como o Cirurgião Mortal.", false],
['O navio que a Hancock e as piratas Kuja navegam é chamado de "Perfume Snake".', true],
["Miss Goldenweek nasceu no West Blue.", false],
["A recompensa do X-Drake é de 220,200,000 de berry.", false],
["A comida favorita da Sugar é laranja.", false],
["Boa Hancock é a capitã das Piratas Kuja e a única mulher membro dos Shichibukai", true],
["[GLA] O jogo Grand Line Adventures foi lançado em Agosto de 2018.", true],
["Kalgara foi revelado como um usuário de Haki da Observação.", true],
["[GLA] Você não pode trocar sua página de equipamentos em uma Zona Segura.", false],
["Chopper foi o sexto membro a entrar na tripulação dos Chapéus de Palha", true],
["Wapol nasceu no North Blue.", false],
["Bartholomew Kuma era conhecido como um Pacifista.", false],
["A recompensa do Mont Blanc Cricket é desconhecida.", false],
["[GLA] Monkey D. Luffy NÃO pode quebrar  paredes com a habilidade Gomu Gomu no Ono.", true],
["O nome verdadeiro da Miss Goldenweek é Marianne.", true],
["O nome verdadeiro da Miss Merry Christmas é Marianne.", false],
["Magellan como a Moku Moku no mi?", false],
["Magellan comeu a Moku Moku no mi?", false],
['O nome do Navio que Mr.5 e Miss Valentine usavam em suas operações era "Pop Rock Candy" ?', true],
['Koala é uma "oficial" do exercito revolucionario ?', true],
["[GLA] você pode construir uma caixa de musica por 200 moedas piratas no mercado negro ? ", false],
["A recompensa do Senor Pink era de 58.000.000 de berry antes de congelada em razão do Doflamingo ter se tornado Shichibukai ?", true],
['O nome do navio que os piratas Donquixote  usaram nos dias deles no North Blue era  "Flamingo Family" ?', false],
["[GLA] Sanji pode se curar com a habilidade Master Cook ?", false],
["Todos os chapeus de palha possuem um skin de Strong World ?", false],
["[GLA] Pufferfish e Shark são considerados monstros nível 3.", false],
["[GLA] Em regra, a quinta habilidade do personagem é desbloqueada no nível 30", true],
["Whale Shark é considerade um monstro nível 3.", true],
["[GLA] Snowflakes é o nome do animal de estimação do Sora.", false],
["[GLA] Atualmente existem somente 10 personagens Bronze disponíveis.", false],
["A rotação muda toda sexta-feira.", true],
["[GLA] Bastão do Rei Macaco é um item que pode ser usado apenas por lutadores.", false],
["[GLA] Não há um Marine Announcer em Conomi Island.", false],
["[GLA] O NPC Magra pede 4 orelhas de lobo na missão dele em Foosha Village.", false],
["[GLA] É possivel criar medalhas dinâmicas de ouro por 15 moedas piratas no mercado negro.", false],
["[GLA] É possível criar medalhas dinâmicas de diamante por 50 moedas piratas no mercado negro. ", true],
["Doutor Hiruluk nasceu em Drum Island.", false],
["Smoker comeu a doku doku no mi", false],
["Kuro causa 20% a mais de dano atacando o inimigo pelas costas.", true],
["Kuro ganha 25% a mais de dano atacando o inimigo pelas costas.", false],
['[GLA] O nome de todas as habilidades do Capone Gang Bege começam com a letra "C", exceto a Big Father', true],
["[GLA] Não é possível entrar na mansão de Kaya.", false],
["[GLA] Marshall D. Teach ganha 30% de ataque e perde metade da armadura quando sua passiva é ativada.", false],
["[GLA] Marshall D. Teach ganha 25% de ataque e perde metade da armadura quando sua passiva é ativada.", false],
['O principal navio do exercito revolucionario é chamado de "Viento Granmar"', false],
["Antes dos eventos da guerra, laffitte tinha uma recompensa de 42.000.000 de berry ?", false],
["A quarta recompensa de Monkey D. Luffy é de 400.000.000 de berry ?", true],
["[GLA] Piiman, um dos piratas do usopp, da algumas missões em Syrup Village ?", false],
["Damaro Black,  Manjaro, chocolat,  drip, turco, cocoa, Mountmountain e Nora Gitsune são os nomes verdadeiros da falsa tripulação dos chapeus de palha?", false],
["[GLA] Trafalgar Law não pode usar nenhuma habilidade quando esta fora do room?", false],
["Boa Marigold e Boa Sandersonia tem somente Haki do armamento ?", false],
["Brook é mais alto do que Franky depois do TimeSkip ?", true],
['Doflamingo e Baby five tiveram uma "complexa" relação amorosa ?', false],
["Tamago comeu a cuma cuma no mi, que o permite ciclar em diferentes formas ?", false],
["Kuzan nasceu na Grand line ?", false],
["Laboon é femea ?", false],
["Monkey D. Luffy foi a única pessoa a escapar de Impel Down na história.", false],
["Luffy tem uma fruta do Diabo do tipo Paramecia.", true],
["Monkey D. Luffy nasceu em Nanko Village. ", false],
["[GLA] A habilidade Motivation aumenta a velocidade do Luffy por 4 segundos e concede bônus de força no próximo ataque.", false],
["[GLA] A habilidade Preparation aumenta a velocidade do Luffy por 4 segundos e concede bônus de força no próximo ataque.", true],
["Monkey D. Luffy nasceu em Foosha Village ", true],
["[GLA] Nanashaku Jitte é um item de nivel 70 que pode ser usado por todas as classe ?", false],
["Lucky Roo nasceu no South Blue ?", true],
["Dororo é um personagem de One Piece", false],
["[GLA] É possível criar poção media de exp, poção grande de exp e poção pequena de exp no mercado negro", false],
["A recompensa dos irmãos Nyaban é de 7.000.000 de berry ?", true],
["Trafalgar Law já foi um escravo ?", false],
["A recompensa do Kuro é de 16.000.000 de berry?", true],
["Zoro empunhou menos de 8 espadas no anime", false],
["Caesar liberou um gas não letal em Punk Hazard", true],
["Issho comeu a fuji fuji no mi, que permite manipular a gravidade ?", false],
["Monkey D. Garp nasceu em South Blue ?", false],
["A recompensa do DELLINGER era de 15.000.000 de berry antes de ser congelada em razão do Doflamingo ter se tornado Shichibukai ?", true],
["[GLA] O kit de reparo 3.0 restaura 1.000 pontos de vida do seu navio por segundo?", false],
["Teach foi o responsável por cicatrizar o olho de Shanks com sua arma de garras?", true],
["[GLA] Você precisa vence com uma equipe de mulheres, para completar a conquista da Pirata Armada?", true],
["Kuma é conhecido como Tirano?", true],
["Caesar comeu a Gasu Gasu no Mi.", true],
["Giolla criou Dellinger praticamente sozinha, fazendo com que ele pensasse que era uma menina, razão pela qual ele se tornou tão feminino ?", true],
["Moomoh é macho ?", true],
["Foxy comeu a Noro Noro no Mi.", true],
["Marco comeu a Pori Pori no Mi, tipo: Fenix, uma Zoan Mítica.", false],
["Rosinante comeu a Nagi Nagi no Mi.", true],
["A Gura Gura no Mi é também conhecida como a mais forte das Paramecia, igual a uma Logia. Sengoku afirmou que ela é poderosa o suficiente para destruir o mundo.", true],
["Machvise comeu a Hon Hon no Mi.", false],
["Monet comeu a Yuki Yuki no Mi", true],
["Monet comeu a Hie Hie no Mi. ", false],
["A recompensa do Mr.2 é de 30,000,000 de berry.", false],
["Miss Goldenweek fez dupla com o Mr.2 em razão das habilidades dela de pintar as criações de cera, tornando-as mais realistas.", false],
["O nome verdadeiro do Mr.5 é Gem.", true],
["Doflamingo era um Tenryubito.", true],
["Franky foi o primeiro ciborgue a aparecer na série", false],
["Franky destruiu a planta de Uranus", false],
["A recompensa do Kuma é de 296.000.000 berries", true],
["GLA Bartolomeu Kuma lê sua bíblia durante sua animação do seu emote", true],
["Kuma já foi um rei", true],
["Franky é um robô.", false],
["GLA Você precisa vencer com um time de especialistas para completar a conquista dos Piratas do Arlong.", false],
["Arlong ja foi escravo.", false],
["Boa Hancock tem referencias com a mitologia grega", true],
["A recompensa de Boa Hancock e de 79.000.000,00", false],
["A terceira recompensa do Monkey D. Luffy foi de 400,000,000 de berry.", false],
["A mãe do Monkey D. Luffy ainda não foi revelada.", true],
["Monkey D. Luffy nasceu em Nanko Village.", false],
["Gum-Gum Fruit é o nome oficial da Fruta do Diabo do Luffy em inglês", true],
["Caso o One Piece fosse ambientado no mundo real, o Luffy seria do Brasil.", true],
["A recompensa de Miss GoldenWeek é de 29.000.000 de Berry ?", true],
["Mr.9 nasceu em Weast Blue ?", true],
["A recompensa de Mr.5 é de 10.000.000 de Berry ?", true],
["[GLA] Você pode ouvir o Chouchou latindo ao falar com ele?", true],
["Sengoku comeu a Bito Bito no mi, uma fruta do tipo zoan mitica?", false],
["Buffalo nasceu no South Blue?", false],
["Mr.5 nasceu no South Blue", true],
["Dentre os piratas do chapeu de palha, Luffy é o favorito de Eichiro Oda", false],
["Foxy nasceu em South Blue", true],
["Trafalgar Law é membro dos chapeu de palha?", false],
["A Boa Hancock é a imperatriz de Amazon Lily, e por isso é conhecida como Imperatriz Pirata?", true],
["O smoker assim como o Fujitora, tenciona acabar com o sistema de Shichibukais?", true],
["A recompensa de Capone Gang Bege é de 300.000.000 de berry ?", true],
["Miss Valentine nasceu na Grand Line ?", false],
["[GLA] Leo, discipulo de Carmem esta na biblioteca de loguetown?", false],
["[GLA] Henry Needle, Henry Blazer, henry Striper, Henry Ford são nomes de algumas habilidades do Niji ?", false],
["A rumble Ball dura 3 minutos?", true],
["Chopper é um guaxinim que comer a fruta human-human ?", false],
["A recompensa de Olivia é de 79.000.000 de berrys, o mesmo que sua filha Nami recebeu depois...", false],
["[GLA] Você precisa derrotar 50 cobras na missão do Coby?", false],
["Gin é capitão dos piratas Gin? ", false],
["A comida favorita da Maruni é queijo ?", true],
["[GLA] Cocoyasi Village é recomendada para jogadores de nivel 50-60 no minimapa do jogo?", true],
["[GLA] Barba Negra tem as seguinte classes: Especialista, Bruiser e atirador, a ultima é porque ele tem um revolver.", false],
["Shanks tem uma cicatriz no olho direito", false],
["A recompensa de Daz Bones é de 70.000.000 de berrys?", false],
["Madame Shyarly é uma das unicas irmãs do Arlong ?", false],
["Pappag é um caçador de recompensas que apareceu no arquipelago sabaody? ", false],
["Monkey D. Garp é o verdadeiro pai de luffy ?", false],
["Shoujou nasceu no north blue?", true],
["Gekko Moriah tem a recompensa de 320.000.000 de berry?", true],
["O verdadeiro nome de Miss Doubleflinger é Paula?", false],
["Bepo não é um mink.", false],
["[GLA] Chabo é o nome da criança que a Nojiko  pede para ajudar no Arlong Park?", true],
["Em termos simples, Haki é a habilidade de sentir energia espiritual (busoshoku), usar força espiritual (Haoshoku) e dominar inimigos (Kenbunshoku).", false],
["Buggy é capitão dos piratas do Buggy e também colíder  da aliança do Buggy e Alvida.", true],
["Genzo nasceu no North Blue?", false],
["[GLA] Nami não pode usar a habilidade Fata Morgana enquanto Mirage Tempo estiver ativa? ", true],
["Johnny e Yosaku nasceram no East Blue?", false],
["[GLA] Em Cocoyasi tem os seguintes monstros: Alligators, Fishmans, Panthers, Baby Octopus e Wolves?", true],
["Brook era capitão dos piratas rumbar?", true],
["Arlong é o unico individuo conhecido que foi liberado de impel down?", false],
["A recompensa do Urougue  é de 100,000,000 berry?", false],
["Existem três tipos de haki para todo mundo", false],
["Duval é o irmão de sanji?", false],
["[GLA] Genzo vende bandana de tritão, calça de tritão, anel do mar e turbante do mar por 5200 berry cada?", true],
["[GLA] É possível criar medalhas dinâmicas de prata por 10 moedas piratas no mercado negro?", true],
["[GLA] É possível criar medalhas dinâmicas de ouro por 20 moedas piratas no mercado negro?", true],
["[GLA] Boa Hancok pode transformar os inimigos em pedra por 7 segundos com a habilidade Mero Mero Mellow?", true],
["Caribou nasceu na grand line?", false],
["Dracule Mihawk teve 2 dubladores no anime?", true],
["Caribou nasceu no north blue?", true],
["Pagaya é pai de Conis", true],
["Shanks é membro dos Yonko que governam o novo mundo e é capitão dos piratas do Ruivo.", true],
["[GLA] O kit de reparo 2.0 restaura 22.500 pontos de vida do seu navio em 30 segundos?", false],
["[GLA] A habilidade de nivel 100 do Arlong, Shark On Tank, imobiliza o inimigo.", false],
["Charlotte Shujan é filho da BigMom", false],
["Ton ton no mi é superior a kilo kilo no mi ?", true],
["Donquixote Doflamingo é capitão dos piratas Donquixote?", false],
["São 28 conquistas da sm?", true],
["Barba Negra nasceu na grand line?", true],
["Zephyr é o unico almirante que nao comeu uma fruto do diabo?", true],
["Franky é o mais alto da tripulação?", false],
["Arlong tem uma irmã conhecida?", true],
["Ninjin era ex-capitão dos piratas usopp?", false],
["Inazuma nasceu no east blue?", false],
["O nome verdadeiro da Miss Valentine e Mikita?", true],
["Pappag é uma estrela do mar que é mascote de Camie e professor. Ele é o criador da linha de moda Criminal e é mentor de Camie para ser uma designer de moda", true],
["Pagaya é Uma estrela do mar e conhecida como professor ?", false],
["Smoker é conhecido como caçador cinza?", false],
["Pappag é uma estrelar do mar?", true],
["Crocodile estava interessado na arma urano?", false],
["Buggy é um shichibukai?", false],
["O NPC Sora em Samui Island e uma menina?", false],
['[GLA] Luffy quando usa sua habilidade "Preparation" Se torna mais veloz e seu próximo ataque da mais dano.', true],
["Sanji em sua infância teve a mesma dubladora do Chopper.", true],
["Magellan nasceu na Grand Line.", true],
["Recompensa dos Irmãos Nyaban é de 7.000.000 de berries.", true],
["[GLA] Em Conomi Island tem os seguintes monstros: Wolf,Mole e Baby Mole.", true],
["Arlong possui um cabelo roxo.", false],
["Aokiji possui uma fruta do diabo do tipo Logia.", true],
["Squard nasceu em North Blue. ", false],
["[GLA] Monkey D.Luffy pode quebrar paredes com a habilidade Gomu Gomu no Ono.", false],
["Mr.3 Wax é tão duro quanto ferro.", true],
["Sanji foi o quinto membro a se juntar aos Piratas do Chapéu de Palha.", false],
["Caribou nasceu em North Blue.", true],
["[GLA] Sapi é o NPC que vende atum em Loguetown.", true],
["Gol D. Roger foi o primeiro rei dos piratas.", true],
["Tralfagar Law perdeu um braço no arco de Dressrosa.", true],
["Kizaru comeu a Pika Pika no Mi.", true],
["Tralfagar Law comeu a Ope Ope no Mi.", true],
["Os Smiles eram feitos por Doflamingo.", false],
["Van Augur nasceu no West Blue.", false],
["Paggy é um caçador de recompensa que aparece no Arquipélago Sabaody.", false],
["[GLA] O Pearl é o primeiro inimigo a se enfrentar na Pirata Armada.", false],
["[GLA] Você completa com um time de especialistas a conquista do Black Cat.", true],
["[GLA] Você pode trocar sua página de equipamentos em uma zona segura.", true],
["Boa Hancock tem mesma dubladora da Reiju.", false],
["A cor do cabelo do Edward Newgate (Barba Branca) era loiro ?", true],
["Marco nasceu na grand line.", true],
["Urouge é conhecido como Mad Monk e capitão dos piratas Mad Monk.", false],
["Boa Hancock é capitã das Piratas Kujas e 2° mulher no grupo dos Shichibukais.", false],
["Silvers Rayleigh tem uma esposa no Arquipelago Sabaody.", true],
["[GLA] Bege libera uma habilidade no level 100.", true],
["Dracule Mihawk é um membro dos piratas do Ruivo.", false],
["Inazuma nasceu no North Blue.", false],
["Eustass Kid perdeu seu braço direito.", false],
["Porco Gourmet é o prato mais demorado para cozinhar em baratie levando 9 minutos.", true],
["Baby Five Comeu a Boku Boku no Mi.", false],
["[GLA] Para evoluir um personagem de 1 para 5 estrelas é necessário 840 fragmentos no total.", true],
["Hancock é a primeira personagem feminina da série capaz de usar todas as três formas de Haki.", true],
["Alvida é a antiga Capitã dos piratas do Buggy. ", false],
["Portgas D. Ace é filho de Rouge.", true],
["Tralfagar Law perdeu um braço durante o Time-Skip", false],
["O sonho de Crocodile era ser Rei dos Piratas.", true],
["A akuma no mi do Pika é do tipo Paramecia.", true],
["A atual recompensa de Marshall D. Teach é de 2.247.600 de berries.", true],
['[GLA] Urouge usa a habilidade "Pray" para curar aliados e remover lentidão e queimaduras.', true],
["Já teve um crossover entre One Piece e Dragon Ball?", true],
["Pearl é o comandante da segunda unidade dos Piratas da Armada Pirata.", false],
["Lucky roo é um membro dos piratas do Ruivo.", true],
["Joy Boy tentou levantar a Noah com a ajuda de Poseidon, mas ele quebrou sua promessa com a ilha dos tritoes.", true],
["[GLA] Carne de Porco Gourmet é a comida mais demorada para cozinhar no baratie. Demora 8 Minutos.", false],
["Luffy ganhou sua cicatriz por causa de um tigre em Foosha Village. ", false],
["[GLA] Em geral os emotes são liberados level 40.", false],
["Joy Boy foi mencionado no Ryugu Poneglyph lido por Nico Robin na floresta do Oceano.", true],
["O cabelo do Trebol é preto.", true],
["Smoker nasceu no east blue.", false],
["O canhão do Mr.4  comeu uma fruta do diabo e se tornou um cachorro.", true],
["Baratie é recomendado para players do lvl 43 ao 50. ", false],
["Chess nasceu no West Blue?", false],
["One Piece é o maior anime do mundo ?", false],
["O Prefeito de Foosha Village é quem da o Tutorial do início do game ?", false],
["A Recompensa de Dadan é 7.800.000 de Berries ? ", true],
["Sabo enfrentou Rob Lucci depois do time skip.", true],
["A Recompensa de Hatchan é de 7.000.000 de berries.", false],
["[GLA] Lâmina Escondida é um item que pode ser usado por todas as Classes.", false],
["Charlotte Linlin é filha da Big Mom.", false],
["[GLA] Island of Rare Animals é recomendada para jogadores do level 38 a 52 no minimapa do game ?", true],
["[GLA] O jogo está traduzido para os seguintes idiomas: Inglês,Português,Espanhol e Polonês ? ", true],
["Bartholomew Kuma tinha a fruta do diabo do espelho ?", false],
["[GLA] Loguetown é recomendada para jogadores de level 56-70 no minimapa do game ?", false],
["A segunda recompensa de Monkey D. Luffy foi de 100.000.000 de berries ?", true],
["Boodle é prefeito de Syrup Village ?", false],
["A recompensa de Miss Doublefinger é de 35.000.000 berrys?", true],
["Existem 8 henchmans no black market?", true],
['Buchi usa a skill "take a lead" (algo assim) para chamar o Sham', false],
["Primeiro beijo da Sanji foi com a Pudding?", true],
["O Primeiro Beijo conhecido de Sanji foi com Violet.", false],
["Crocodile é um dos Shichibukais originais a possuir Logia ?", false],
["[GLA] Killer causa 4x mais sangramento usando Bloody Cuts ou Kira Nokogiri.", false],
["Kuro capitão dos Piratas Black Cat é também conhecido por seu apelido de Klahador ?", true],
["[GLA] você pode encontrar  8 instacias do black market em eastblue?", false],
["A Yubashiri (Espada de Zoro) Enferrujou?", true],
["Sanji nasceu no north blue.", true],
["Vinsmoke Reiju é usuária de akuma no mi?", true],
["Nerfetari Vivi faz parte do bando dos chapéu de palha?", false],
["Recompensa da Nami é de 66,000,000 berry?", true],
["Ace comeu a Mira Mira no Mi", false],
["Doflamingo era Capitão dos Piratas Donquixote ?", true],
["Vergo conhece Doflamingo desde criança ?", true],
["Luffy realmente nasceu em foosha ?", true],
["Diamond Jozu nasceu na Grand Line ?", false],
["[GLA] Kumo Island é recomendada para jogadores de level 64 a 70 in the game minimap.", false],
["O doflamingo foi o primeiro personagem a despertar sua fruta do diabo.", false],
["Catarina devon nasceu na grand line?", false],
["Shanks é membro dos Yonko que governam o novo mundo e é capitão dos piratas do Shanks", false],
["O verdadeiro nome do Mr.3 é Galdino", true],
["Erik é um personagem non-canon de One piece.", false],
["Mihalk possuiu apenas um tradutor no anime?", false],
["Há seis níveis em impel down?", true],
["Recompensa do Jinbei é de 439,000,000 Berries?", false],
["Boa Hancock usa Haki do Rei ?", true],
["Jango é um marinheiro e o ex-capitão do Black Cack Pirates.", false],
["Recompensa do X Drake é 220,20,207 berries", false],
["Doflamingo matou gekko moria?", false],
["Buggy tem a maior recompensa ente os Shichibukais?", false],
["Masira nasceu no North Blue?", true],
["A primeira recompensa do Chopper foi de 50 berries?", true],
["Capangas do Capone ficam imunes durante o Big Father?", false],
["Tashigi nasceu no East Blue?", true],
["Woop Slap é prefeito de Orange Town ?", false],
["Crocus nasceu na Grand Line ?", true],
['Tralfagar Law é conhecido por ser o "Cirurgião da Morte"', true],
["O verdadeiro nome do Mr.2 é Bon Clay Bentham ? ", true],
["Luffy tem uma fruta do Diabo do tipo Logia que tornou seu corpo de borracha.", false],
["O Yonkou Shanks é conhecido por ser o Capitão dos Piratas do Shanks ?", false],
["Mr. 1 comeu a supa supa no mi?", true],
["Ace realmente nasceu em Baterilla ?", true],
["Kizaru nasceu na grandline ?", false],
[`A habilidade "Usopp's Fear" concede a ele velocidade e defesa?`, true],
["Jango é um marinheiro e ex-imediato do capitão Kuro?", true],
]